### ISSUE TITLE
Exposing credentials

### ISSUE THREAD

**Issue by niyumard** [psamim/dotfiles#2]
سلام
توی کانفیگ doom/config.el فکر کنم راه ورود به گوگل کلندرت رو گذاشتی
نمیدونم کار میکنه یا نه ولی پاک کنی شاید بهتر باشه
دمتم گرم بابت کانفیگ عالیت :+1:

**Comment by niyumard** [comment]
خب ظاهرا #1 همینه دقیقا
بیخیال پس :)

**Comment by psamim** [comment]
@niyumard 
ممنون حسین جان. آره فکر نکنم مشکلی باشه. فربانت لطف داری.
